name: Build Windows x64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        # We put the code in a 'morph_dict' folder to make includes work
        path: morph_dict

    - name: Install Dependencies via vcpkg
      run: vcpkg install zlib:x64-windows plog:x64-windows

    - name: Configure CMake
      run: >
        cmake -S morph_dict -B build -A x64 
        -DCMAKE_BUILD_TYPE=Release 
        -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
        -DWIN32=ON
        -DCMAKE_CXX_FLAGS="/I${{ github.workspace }} /DWIN32 /utf-8 /EHsc"
        -DCMAKE_C_FLAGS="/I${{ github.workspace }} /DWIN32 /utf-8"
        
    - name: Build
      run: cmake --build build --config Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: morph_dict-windows-x64
        path: build/Release/
